use_default_settings: true

general:
  instance_name: 'KatsuSear'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  secret_key: 'b67d066a1fe087f837e1648ea189ae15a4bf0a5cbde1c569e6c1d5f18b5fe1b0' # Is overwritten by ${SEARXNG_SECRET}

engines:
  - name: wolframalpha
    disabled: false
